# Generated by Django 5.2.7 on 2026-03-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='ThemePreference',
        ),
    ]
