# Generated by Django 5.2.7 on 2026-03-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auditlog_themepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
    ]
