# Generated by Django 5.2.12 on 2026-04-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_authorizedmember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedmember',
            name='photo',
        ),
    ]
